package net.runelite.client.plugins.microbot.ocboltenchant;

import net.runelite.api.gameval.ItemID;

public enum BoltType
{
    OPAL("Opal bolts", ItemID.OPAL_BOLT, ItemID.XBOWS_CROSSBOW_BOLTS_BRONZE_TIPPED_OPAL_ENCHANTED, 4),
    OPAL_DRAGON("Opal dragon bolts", ItemID.DRAGON_BOLTS_UNENCHANTED_OPAL, ItemID.DRAGON_BOLTS_ENCHANTED_OPAL, 4),
    SAPPHIRE("Sapphire bolts", ItemID.XBOWS_CROSSBOW_BOLTS_MITHRIL_TIPPED_SAPPHIRE, ItemID.XBOWS_CROSSBOW_BOLTS_MITHRIL_TIPPED_SAPPHIRE_ENCHANTED, 7),
    SAPPHIRE_DRAGON("Sapphire dragon bolts", ItemID.DRAGON_BOLTS_UNENCHANTED_SAPPHIRE, ItemID.DRAGON_BOLTS_ENCHANTED_SAPPHIRE, 7),
    JADE("Jade bolts", ItemID.XBOWS_CROSSBOW_BOLTS_BLURITE_TIPPED_JADE, ItemID.XBOWS_CROSSBOW_BOLTS_BLURITE_TIPPED_JADE_ENCHANTED, 14),
    JADE_DRAGON("Jade dragon bolts", ItemID.DRAGON_BOLTS_UNENCHANTED_JADE, ItemID.DRAGON_BOLTS_ENCHANTED_JADE, 14),
    PEARL("Pearl bolts", ItemID.PEARL_BOLTS, ItemID.XBOWS_CROSSBOW_BOLTS_IRON_TIPPED_PEARL_ENCHANTED, 24),
    PEARL_DRAGON("Pearl dragon bolts", ItemID.DRAGON_BOLTS_UNENCHANTED_PEARL, ItemID.DRAGON_BOLTS_ENCHANTED_PEARL, 24),
    EMERALD("Emerald bolts", ItemID.XBOWS_CROSSBOW_BOLTS_MITHRIL_TIPPED_EMERALD, ItemID.XBOWS_CROSSBOW_BOLTS_MITHRIL_TIPPED_EMERALD_ENCHANTED, 27),
    EMERALD_DRAGON("Emerald dragon bolts", ItemID.DRAGON_BOLTS_UNENCHANTED_EMERALD, ItemID.DRAGON_BOLTS_ENCHANTED_EMERALD, 27),
    TOPAZ("Topaz bolts", ItemID.XBOWS_CROSSBOW_BOLTS_STEEL_TIPPED_REDTOPAZ, ItemID.XBOWS_CROSSBOW_BOLTS_STEEL_TIPPED_REDTOPAZ_ENCHANTED, 29),
    TOPAZ_DRAGON("Topaz dragon bolts", ItemID.DRAGON_BOLTS_UNENCHANTED_TOPAZ, ItemID.DRAGON_BOLTS_ENCHANTED_TOPAZ, 29),
    RUBY("Ruby bolts", ItemID.XBOWS_CROSSBOW_BOLTS_ADAMANTITE_TIPPED_RUBY, ItemID.XBOWS_CROSSBOW_BOLTS_ADAMANTITE_TIPPED_RUBY_ENCHANTED, 49),
    RUBY_DRAGON("Ruby dragon bolts", ItemID.DRAGON_BOLTS_UNENCHANTED_RUBY, ItemID.DRAGON_BOLTS_ENCHANTED_RUBY, 49),
    DIAMOND("Diamond bolts", ItemID.XBOWS_CROSSBOW_BOLTS_ADAMANTITE_TIPPED_DIAMOND, ItemID.XBOWS_CROSSBOW_BOLTS_ADAMANTITE_TIPPED_DIAMOND_ENCHANTED, 57),
    DIAMOND_DRAGON("Diamond dragon bolts", ItemID.DRAGON_BOLTS_UNENCHANTED_DIAMOND, ItemID.DRAGON_BOLTS_ENCHANTED_DIAMOND, 57),
    DRAGONSTONE("Dragonstone bolts", ItemID.XBOWS_CROSSBOW_BOLTS_RUNITE_TIPPED_DRAGONSTONE, ItemID.XBOWS_CROSSBOW_BOLTS_RUNITE_TIPPED_DRAGONSTONE_ENCHANTED, 68),
    DRAGONSTONE_DRAGON("Dragonstone dragon bolts", ItemID.DRAGON_BOLTS_UNENCHANTED_DRAGONSTONE, ItemID.DRAGON_BOLTS_ENCHANTED_DRAGONSTONE, 68),
    ONYX("Onyx bolts", ItemID.XBOWS_CROSSBOW_BOLTS_RUNITE_TIPPED_ONYX, ItemID.XBOWS_CROSSBOW_BOLTS_RUNITE_TIPPED_ONYX_ENCHANTED, 87),
    ONYX_DRAGON("Onyx dragon bolts", ItemID.DRAGON_BOLTS_UNENCHANTED_ONYX, ItemID.DRAGON_BOLTS_ENCHANTED_ONYX, 87);

    private final String name;
    private final int itemId;
    private final int enchantedId;
    private final int level;

    BoltType(String name, int itemId, int enchantedId, int level)
    {
        this.name = name;
        this.itemId = itemId;
        this.enchantedId = enchantedId;
        this.level = level;
    }

    public int getItemId() { return itemId; }
    public int getEnchantedId() { return enchantedId; }
    public int getLevel() { return level; }
    public String getEnchantedName() { return name + " (e)"; }

    @Override
    public String toString() { return name; }
}

